version: '3.8'

services:
  zaproxy:
    image: ghcr.io/zaproxy/zaproxy:stable
    container_name: zaproxy
    ports:
      - "8090:8090"  # Port OWASP ZAP API
    command: zap.sh -daemon -port 8090 -host 0.0.0.0
    volumes:
      - zap_data:/zap/wrk
    networks:
      - zap_network

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: telcoinfo_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - zap_network

  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    restart: always
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://postgres:5432/sonarqube
      SONAR_JDBC_USERNAME: postgres
      SONAR_JDBC_PASSWORD: password
    ports:
      - "9000:9000"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - sonarqube_data:/opt/sonarqube/data  
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_extensions:/opt/sonarqube/extensions
    networks:
      - zap_network

volumes:
  zap_data:
  postgres_data:
  sonarqube_data:
  sonarqube_logs:
  sonarqube_extensions:

networks:
  zap_network:
    driver: bridge

