apiVersion: v1
kind: Service
metadata:
  name: telco-service
spec:
  selector:
    app: telco-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
      nodePort: 30080  # Expose sur un port accessible
  type: NodePort

