apiVersion: apps/v1
kind: Deployment
metadata:
  name: telco-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: telco-app
  template:
    metadata:
      labels:
        app: telco-app
    spec:
      containers:
        - name: telco-container
          image: omarelhedfi/telcoinfo:latest  # Update this with your actual Docker image
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: telco-service
spec:
  selector:
    app: telco-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
